version: '3'

services:

  client:
    image: inchiresolver/inchiresolver:${DJANGO_APP_VERSION}
    container_name: inchiresolver-client
    volumes:
      - ${DJANGO_APP_HOME}:/home/app
      - ${CHEMBIENCE_SPHERE}:/home/sphere
      - ${CHEMBIENCE_SHARE}:/share
    ports:
       - ${DJANGO_APP_CONNECTION_PORT}:80
    networks:
      - sphere
    environment:
      - CHEMBIENCE_UID
      - CHEMBIENCE_GID
      - CHEMBIENCE_DB_USER
      - CHEMBIENCE_DB_HOST
      - CHEMBIENCE_DB_PORT
      - CHEMBIENCE_DB_PASSWORD
      - APP_VIRTUAL_HOSTNAME=${DJANGO_APP_VIRTUAL_HOSTNAME}
      - VIRTUAL_HOST=${DJANGO_APP_VIRTUAL_HOSTNAME}
      - LETSENCRYPT_HOST
      - LETSENCRYPT_EMAIL
      - LETSENCRYPT_TEST
      - INCHI_RESOLVER_HOST
      - INCHI_RESOLVER_USER
      - INCHI_RESOLVER_PASSWD
    entrypoint: ["/home/app/docker-entrypoint.client.sh"]
    command: ["python"]

networks:
  sphere:
