version: '3'

services:

  inchiresolver:
    image: inchiresolver/inchiresolver:${DJANGO_APP_VERSION}
    container_name: inchiresolver
    volumes:
      - ${DJANGO_APP_HOME}:/home/app
      - ${CHEMBIENCE_SPHERE}:/home/sphere
      - ${CHEMBIENCE_SHARE}:/share
    ports:
       - ${DJANGO_APP_CONNECTION_PORT}:80
    networks:
      - sphere
    environment:
      - CHEMBIENCE_UID
      - CHEMBIENCE_GID
      - CHEMBIENCE_DB_USER
      - CHEMBIENCE_DB_HOST
      - CHEMBIENCE_DB_PORT
      - CHEMBIENCE_DB_PASSWORD
      - APP_VIRTUAL_HOSTNAME=${DJANGO_APP_VIRTUAL_HOSTNAME}
      - VIRTUAL_HOST=${DJANGO_APP_VIRTUAL_HOSTNAME}
      - LETSENCRYPT_HOST
      - LETSENCRYPT_EMAIL
      - LETSENCRYPT_TEST
      - INCHI_RESOLVER_HOST
      - INCHI_RESOLVER_USER
      - INCHI_RESOLVER_PASSWD
      - INCHI_RESOLVER_NAVBAR_TITLE
      - INCHI_RESOLVER_NAVBAR_COLOR
    depends_on:
      - inchiresolverdb
    entrypoint: ["/home/app/docker-entrypoint.sh"]
    command: ["/home/nginx/run.sh"]


  inchiresolverdb:
    image: chembience/db:${CHEMBIENCE_VERSION}
    container_name: inchiresolverdb
    volumes:
      - inchiresolverdb_volume:/var/lib/postgresql
    networks:
      - sphere
    environment:
      - DEBUG=false
      - CHEMBIENCE_UID
      - CHEMBIENCE_GID
      - DB_USER=${CHEMBIENCE_DB_USER}
      - DB_PASS=${CHEMBIENCE_DB_PASSWORD}
      - DB_NAME=${CHEMBIENCE_DB_USER}
      - DB_TEMPLATE=
      - DB_EXTENSION=rdkit
      - REPLICATION_MODE=
      - REPLICATION_USER=
      - REPLICATION_PASS=
      - REPLICATION_SSLMODE=

volumes:
  inchiresolverdb_volume:

networks:
  sphere:
