version: '3'

services:

  inchiresolver:
    image: inchiresolver/inchiresolver:${DJANGO_APP_VERSION}
    container_name: inchiresolver
    volumes:
      - ${DJANGO_APP_HOME}:/home/app
      - ${CHEMBIENCE_SPHERE}:/home/sphere
      - ${CHEMBIENCE_SHARE}:/share
    ports:
       - ${DJANGO_APP_CONNECTION_PORT}:80
    networks:
      - sphere
    environment:
      - CHEMBIENCE_UID
      - CHEMBIENCE_GID
      - CHEMBIENCE_DB_USER
      - CHEMBIENCE_DB_HOST
      - CHEMBIENCE_DB_PORT
      - CHEMBIENCE_DB_PASSWORD
      - APP_VIRTUAL_HOSTNAME=${DJANGO_APP_VIRTUAL_HOSTNAME}
      - VIRTUAL_HOST=${DJANGO_APP_VIRTUAL_HOSTNAME}
      - LETSENCRYPT_HOST
      - LETSENCRYPT_EMAIL
      - LETSENCRYPT_TEST
      - INCHI_RESOLVER_HOST
      - INCHI_RESOLVER_USER
      - INCHI_RESOLVER_PASSWD
      - INCHI_RESOLVER_TITLE
      - INCHI_RESOLVER_COLOR_SCHEME
    depends_on:
      - inchiresolverdb
    entrypoint: ["/home/app/docker-entrypoint.sh"]
    command: ["/home/nginx/run.sh"]


  inchiresolverdb:
    image: chembience/postgres-rdkit:postgres-13.rdkit-2020.09
    container_name: inchiresolverdb
    volumes:
      - inchiresolverdb_volume:/var/lib/postgresql
    networks:
      - sphere
    environment:
      - CHEMBIENCE_UID
      - CHEMBIENCE_GID
      - POSTGRES_USER=${CHEMBIENCE_DB_USER}
      - POSTGRES_PASSWORD=${CHEMBIENCE_DB_PASSWORD}

volumes:
  inchiresolverdb_volume:

networks:
  sphere:
