#!/bin/bash
set -e

source .env

if [ $# -eq 0 ]
  then
    docker-compose -f docker-compose.shell.yml run --rm shell psql -h "cactus-inchiresolverdb" -U chembience chembience
  else
    docker-compose -f docker-compose.shell.yml run --rm shell psql $1
fi

