# Generated by Django 2.2.11 on 2020-07-22 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resolver', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='accepted_mediatypes',
            field=models.ManyToManyField(related_name='accepting_endpoints', to='resolver.MediaType'),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='content_mediatypes',
            field=models.ManyToManyField(related_name='producing_endpoints', to='resolver.MediaType'),
        ),
    ]
