# Generated by Django 2.2.6 on 2020-01-14 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resolver', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inchi',
            name='entrypoints',
            field=models.ManyToManyField(default=None, related_name='inchis', to='resolver.EntryPoint'),
        ),
    ]
