# Generated by Django 2.2.11 on 2020-04-05 16:56

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('resolver', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpoint',
            name='request_methods',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('GET', 'GET'), ('POST', 'POST')], default='GET', max_length=8),
        ),
    ]
