# Generated by Django 2.2.11 on 2020-07-27 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resolver', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='endpoint',
            old_name='accept_header_mediatypes',
            new_name='accept_header_media_types',
        ),
        migrations.RenameField(
            model_name='endpoint',
            old_name='content_mediatypes',
            new_name='content_media_types',
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='entrypoint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='endpoints', to='resolver.EntryPoint'),
        ),
        migrations.AlterField(
            model_name='entrypoint',
            name='publisher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entrypoints', to='resolver.Publisher'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publishers', to='resolver.Organization'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='resolver.Publisher'),
        ),
        migrations.AlterUniqueTogether(
            name='entrypoint',
            unique_together={('parent', 'publisher', 'href')},
        ),
        migrations.AlterUniqueTogether(
            name='publisher',
            unique_together={('organization', 'parent', 'name', 'href', 'orcid')},
        ),
    ]
