# Generated by Django 2.1.2 on 2018-10-08 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resolver', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='parent',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='resolver.Organization'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='organization',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='resolver.Organization'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='parent',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='resolver.Publisher'),
        ),
        migrations.AlterField(
            model_name='uriendpoint',
            name='entrypoint',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='resolver.UrlEntryPoint'),
        ),
        migrations.AlterField(
            model_name='urlentrypoint',
            name='parent',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='resolver.UrlEntryPoint'),
        ),
        migrations.AlterField(
            model_name='urlentrypoint',
            name='publisher',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='resolver.Publisher'),
        ),
    ]
