# Generated by Django 2.2.6 on 2020-02-17 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resolver', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='endpoint',
            old_name='media_type',
            new_name='content_media_type',
        ),
        migrations.AddField(
            model_name='publisher',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
