# Generated by Django 2.2.6 on 2020-01-19 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resolver', '0002_auto_20200114_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inchi',
            name='entrypoints',
            field=models.ManyToManyField(related_name='inchis', to='resolver.EntryPoint'),
        ),
    ]
