# Generated by Django 2.2.11 on 2020-07-23 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resolver', '0002_auto_20200722_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endpoint',
            name='accepted_mediatypes',
        ),
        migrations.RemoveField(
            model_name='endpoint',
            name='content_mediatypes',
        ),
        migrations.AddField(
            model_name='endpoint',
            name='consumer',
            field=models.ManyToManyField(related_name='consumer', to='resolver.MediaType'),
        ),
        migrations.AddField(
            model_name='endpoint',
            name='producer',
            field=models.ManyToManyField(related_name='producer', to='resolver.MediaType'),
        ),
    ]
