# Generated by Django 2.2.6 on 2020-02-17 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resolver', '0002_auto_20200217_2103'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inchi',
            options={'verbose_name': 'InChI'},
        ),
    ]
