# Generated by Django 2.2.6 on 2020-01-08 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resolver', '0002_auto_20200107_2245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publisher',
            old_name='website',
            new_name='href',
        ),
        migrations.AlterField(
            model_name='publisher',
            name='organization',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publishers', to='resolver.Organization'),
        ),
    ]
