# Generated by Django 2.2.11 on 2020-04-05 17:05

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('resolver', '0002_endpoint_request_methods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='request_methods',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('GET', 'GET'), ('POST', 'POST')], default=['GET', 'POST'], max_length=8),
        ),
    ]
