# Generated by Django 2.2.6 on 2019-11-10 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resolver', '0003_auto_20190823_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inchi',
            name='block1',
            field=models.CharField(db_index=True, max_length=14),
        ),
        migrations.AlterField(
            model_name='inchi',
            name='block2',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='inchi',
            name='block3',
            field=models.CharField(db_index=True, max_length=1),
        ),
        migrations.AlterField(
            model_name='inchi',
            name='version',
            field=models.IntegerField(db_index=True, default=1),
        ),
    ]
