# Generated by Django 2.2.6 on 2020-02-17 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resolver', '0003_auto_20200217_2108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inchi',
            old_name='safeopt',
            new_name='safe_options',
        ),
        migrations.AlterUniqueTogether(
            name='inchi',
            unique_together={('block1', 'block2', 'block3', 'version', 'safe_options')},
        ),
    ]
