# Generated by Django 2.2.11 on 2020-07-28 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resolver', '0004_auto_20200727_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrypoint',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='resolver.EntryPoint'),
        ),
    ]
