# Generated by Django 2.2.10 on 2020-03-09 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resolver', '0004_auto_20200217_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrypoint',
            name='category',
            field=models.CharField(choices=[('site', 'site'), ('service', 'service'), ('resolver', 'resolver'), ('parent', 'parent'), ('root', 'root')], default='site', max_length=16),
        ),
    ]
