# Generated by Django 2.2.11 on 2020-07-30 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resolver', '0005_auto_20200728_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='category',
            field=models.CharField(choices=[('schema', 'Schema'), ('uritemplate', 'URI Template (RFC6570)'), ('documentation', 'Documentation (HTML)')], default='uritemplate', max_length=16),
        ),
    ]
