# Generated by Django 2.2.11 on 2020-07-30 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resolver', '0006_auto_20200730_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpoint',
            name='request_schema_endpoint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schema_requesting_endpoints', to='resolver.EndPoint'),
        ),
        migrations.AddField(
            model_name='endpoint',
            name='response_schema_endpoint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schema_responding_endpoints', to='resolver.EndPoint'),
        ),
    ]
